"""initial_schema

Revision ID: f76789c751be
Revises: 
Create Date: 2026-06-19 01:27:03.325651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76789c751be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('complaint_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cuisines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_brands_org_name')
    )
    op.create_index(op.f('ix_brands_org_id'), 'brands', ['org_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'name', name='uq_branches_brand_name')
    )
    op.create_index(op.f('ix_branches_brand_id'), 'branches', ['brand_id'], unique=False)
    op.create_index(op.f('ix_branches_city_id'), 'branches', ['city_id'], unique=False)
    op.create_table('branch_cuisines',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('cuisine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['cuisine_id'], ['cuisines.id'], ),
    sa.PrimaryKeyConstraint('branch_id', 'cuisine_id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('ordered_cuisine', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('price_segment', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wait_time_mins', sa.SmallInteger(), nullable=True),
    sa.Column('feedback_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ordered_cuisine IN ('Indian', 'Thai', 'Italian', 'Chinese', 'Fast Food')", name='ck_feedbacks_ordered_cuisine'),
    sa.CheckConstraint("price_segment IN ('budget', 'mid-range', 'premium')", name='ck_feedbacks_price_segment'),
    sa.CheckConstraint("service_type IN ('delivery', 'dine-in', 'takeaway')", name='ck_feedbacks_service_type'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_feedbacks_rating'),
    sa.CheckConstraint('wait_time_mins IS NULL OR wait_time_mins >= 0', name='ck_feedbacks_wait_time'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedbacks_branch_date', 'feedbacks', ['branch_id', 'feedback_date'], unique=False)
    op.create_index(op.f('ix_feedbacks_ordered_cuisine'), 'feedbacks', ['ordered_cuisine'], unique=False)
    op.create_index(op.f('ix_feedbacks_rating'), 'feedbacks', ['rating'], unique=False)
    op.create_index(op.f('ix_feedbacks_service_type'), 'feedbacks', ['service_type'], unique=False)
    op.create_table('feedback_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('severity_score', sa.SmallInteger(), nullable=True),
    sa.Column('primary_complaint_id', sa.Integer(), nullable=True),
    sa.Column('secondary_complaint_id', sa.Integer(), nullable=True),
    sa.Column('positive_aspects', sa.Text(), nullable=True),
    sa.Column('negative_aspects', sa.Text(), nullable=True),
    sa.Column('classified_by', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("classified_by IN ('rules', 'gemini')", name='ck_analysis_classified_by'),
    sa.CheckConstraint("sentiment IN ('positive', 'neutral', 'negative')", name='ck_analysis_sentiment'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_analysis_confidence_score'),
    sa.CheckConstraint('severity_score BETWEEN 1 AND 5', name='ck_analysis_severity_score'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.ForeignKeyConstraint(['primary_complaint_id'], ['complaint_categories.id'], ),
    sa.ForeignKeyConstraint(['secondary_complaint_id'], ['complaint_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_analysis')
    op.drop_index(op.f('ix_feedbacks_service_type'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_rating'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_ordered_cuisine'), table_name='feedbacks')
    op.drop_index('ix_feedbacks_branch_date', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_table('branch_cuisines')
    op.drop_index(op.f('ix_branches_city_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_brand_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_brands_org_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_table('organizations')
    op.drop_table('cuisines')
    op.drop_table('complaint_categories')
    op.drop_table('cities')
    # ### end Alembic commands ###
